### PR TITLE
Added 2D FSI Solver

### PR DESCRIPTION
**Pull request by wcs211**
Added my latest version of the 2D FSI solver.

### CODE REVIEW

**Comment by kmoored** [comment]
There are a bunch of unused files in the pull request.  Can you get rid of the files that are not necessary and also reorganize your files into a folder structure similar to the master

**Comment by wcs211** [comment]
See commit 6031a36. Excess files have been removed and the file structure made to be similar to master.

**Comment by kmoored** [comment]
I think you have to submit a new pull request.  It looks like the unused
files were still there.

Keith

**Comment by wcs211** [comment]
Something is up because git is saying my BEM2DFSI_v1.1 branch is up-to-date with your master branch, but when you look at the files nothing has changed

**Comment by kmoored** [comment]
I reverted the pull request because after the pull I had all the unused
files as part of the master.  Maybe you should make a new branch and make
another pull request?

Keith

**Pull request merged**
